apiVersion: v1
kind: PersistentVolume
metadata:
  name: ldmeai-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0648289694dda26c4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldmeai-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
